// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlowAPI.Data;

#nullable disable

namespace TaskFlowAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129143857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TaskFlowAPI.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = "2026-01-29 17:38:55",
                            Description = "This is a sample task description.",
                            DueDate = new DateTime(2026, 2, 5, 17, 38, 55, 388, DateTimeKind.Local).AddTicks(6440),
                            IsCompleted = false,
                            Title = "Learn  .NET API"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = "2026-01-29 17:38:55",
                            Description = "This is another task description.",
                            DueDate = new DateTime(2026, 2, 12, 17, 38, 55, 388, DateTimeKind.Local).AddTicks(7883),
                            IsCompleted = false,
                            Title = "Learn React"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
