@base_address = http://localhost:5000/api/Tasks
### Get All Tasks
//GET {{base_address}}
GET {{base_address}}?isCompleted=true

###
POST {{base_address}}
Content-Type: application/json

{
    "title": "Last one for understanding",
    "description": "This is a new task",
    "createdAt": "2024-06-01T10:00:00Z",
    "dueDate": "2024-06-10T10:00:00Z",
    "isCompleted": false
}
### Get Task by ID
GET {{base_address}}/3
### Update Task
PUT {{base_address}}/3
Content-Type: application/json

{
    "id": 2,
    "title": "new Task Title Trial",
    "description": "Updated description",
    "createdAt": "2024-06-01T10:00:00Z",
    "dueDate": "2024-06-15T10:00:00Z",
    "isCompleted": true
}
### Delete Task
DELETE {{base_address}}/1



### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "mm",
  "email": "md@gmail.com",
  "password": "Test123!"
}

###

### Login (to verify register works)
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "mm",
  "email": "md@gmail.com",
  "password": "Test123!"
}

###

### Forgot password
POST http://localhost:5000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "nelliemutethia@gmail.com"
}

###

### Reset password (after you get the token from email)
POST http://localhost:5000/api/auth/reset-password
Content-Type: application/json

{
  "token": "drLgQG68CQb8USYAuhIrjov1bS3976Lpf9J3wr/mATs=",
  "newPassword": "NewPass123!"
}

// get search 


